apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: grafana-config-map
  name: grafana-config-map
  namespace: default
data:
  datasources.yml: |-
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus:9090 
      isDefault: true
      access: proxy
      editable: true
