apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: prom-data
  name: prom-data
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
